<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation [$item, $itemSet, or $media]
 *
 * Any option can be passed to the template.
 * @link https://github.com/dompdf/dompdf
 * @link https://github.com/dompdf/dompdf/blob/HEAD/src/Options.php#L307-L359.
 */

$this->pdfCreator($resource, 'default', []);
